## Import Libraries

In [5]:
!pip install -q keras-tuner

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import keras_tuner as kt

print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.20.0

## Load Dataset

In [6]:
df = pd.read_csv('bengaluru_house_prices.csv')

df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

## Data Preprocessing & Cleaning

In [7]:
df = df.drop(columns=['area_type', 'availability', 'society', 'balcony'])

df = df.dropna()

df['bhk'] = df['size'].apply(lambda x: int(x.split(' ')[0]))
df = df.drop(columns=['size'])

def convert_sqft_to_num(x):
    tokens = str(x).split('-')
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2
    try:
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)
df = df.dropna()

location_stats = df['location'].value_counts()
locations_less_than_10 = location_stats[location_stats <= 10]
df['location'] = df['location'].apply(lambda x: 'other' if x in locations_less_than_10 else x)

df = pd.get_dummies(df, columns=['location'], drop_first=True, dtype=int)

df.head()

,total_sqft,bath,price,bhk,location_1st Block Jayanagar,location_1st Phase JP Nagar,location_2nd Phase Judicial Layout,location_2nd Stage Nagarbhavi,location_5th Block Hbr Layout,location_5th Phase JP Nagar,...,location_Vishveshwarya Layout,location_Vishwapriya Layout,location_Vittasandra,location_Whitefield,location_Yelachenahalli,location_Yelahanka,location_Yelahanka New Town,location_Yelenahalli,location_Yeshwanthpur,location_other
0,1056.0,2.0,39.07,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2600.0,5.0,120.00,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1440.0,2.0,62.00,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1521.0,3.0,95.00,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1200.0,2.0,51.00,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Split Data & Feature Scaling

In [8]:
X = df.drop(columns=['price'])
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"X_train shape: {X_train_scaled.shape}")

X_train shape: (10560, 243)

## Build ANN Model

In [9]:
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │        31,232 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41,601 (162.50 KB)

 Trainable params: 41,601 (162.50 KB)

 Non-trainable params: 0 (0.00 B)

## Train the Model

In [10]:
history = model.fit(X_train_scaled, y_train,
                    validation_split=0.2,
                    epochs=60,
                    batch_size=32,
                    verbose=1)

Epoch 1/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 19434.4160 - mae: 66.2796 - val_loss: 17593.9414 - val_mae: 49.3260
Epoch 2/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 13740.2627 - mae: 47.5411 - val_loss: 16753.4297 - val_mae: 44.4317
Epoch 3/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 12872.0469 - mae: 45.7690 - val_loss: 16983.9062 - val_mae: 42.9884
Epoch 4/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 12665.2588 - mae: 44.1493 - val_loss: 16175.8789 - val_mae: 41.3360
Epoch 5/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 12448.7900 - mae: 43.0264 - val_loss: 15785.5342 - val_mae: 43.9003
Epoch 6/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 12089.8701 - mae: 42.9557 - val_loss: 15474.9043 - val_mae: 40.7461
Epoch 7/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 11597.3535 - mae: 42.0205 - val_loss: 15412.0850 - val_mae: 42.2232
Epoch 8/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 11861.0332 - mae: 42.8547 - val_loss: 15077.5518 - val_mae: 39.8334
Epoch 9/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 11018.9434 - mae: 40.7438 - val_loss: 15280.7910 - val_mae: 39.9083
Epoch 10/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11207.4131 - mae: 41.0239 - val_loss: 14814.4746 - val_mae: 39.1075
Epoch 11/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10853.8789 - mae: 40.6189 - val_loss: 14205.4307 - val_mae: 40.0482
Epoch 12/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10688.0459 - mae: 39.9968 - val_loss: 13870.1357 - val_mae: 39.1279
Epoch 13/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10135.8633 - mae: 39.0466 - val_loss: 13582.8594 - val_mae: 39.1158
Epoch 14/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10133.0938 - mae: 39.4084 - val_loss: 13558.0195 - val_mae: 38.6279
Epoch 15/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10315.1191 - mae: 39.3516 - val_loss: 13506.8984 - val_mae: 43.1893
Epoch 16/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9128.5020 - mae: 38.0043 - val_loss: 13432.9863 - val_mae: 37.5531
Epoch 17/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9291.9004 - mae: 38.0700 - val_loss: 12963.0732 - val_mae: 37.1009
Epoch 18/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9845.8633 - mae: 38.3071 - val_loss: 12839.7246 - val_mae: 36.9745
Epoch 19/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8757.4990 - mae: 37.3846 - val_loss: 13365.3281 - val_mae: 38.4881
Epoch 20/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9040.2188 - mae: 37.6112 - val_loss: 12898.7568 - val_mae: 36.9312
Epoch 21/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8875.1533 - mae: 37.1718 - val_loss: 12296.2354 - val_mae: 38.4087
Epoch 22/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8850.7305 - mae: 37.2382 - val_loss: 12449.6035 - val_mae: 36.5917
Epoch 23/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8984.3398 - mae: 37.0102 - val_loss: 12138.8428 - val_mae: 36.4785
Epoch 24/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8705.6104 - mae: 36.5147 - val_loss: 12154.0762 - val_mae: 39.0919
Epoch 25/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8266.8857 - mae: 36.5566 - val_loss: 12678.8613 - val_mae: 36.7063
Epoch 26/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7836.4429 - mae: 36.0713 - val_loss: 12693.2891 - val_mae: 36.4307
Epoch 27/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8725.1543 - mae: 37.1538 - val_loss: 12616.8262 - val_mae: 42.2508
Epoch 28/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8130.1704 - mae: 36.0685 - val_loss: 12691.1055 - val_mae: 36.9100
Epoch 29/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8048.4961 - mae: 35.9481 - val_loss: 12903.9004 - val_mae: 36.3929
Epoch 30/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8256.1182 - mae: 36.1712 - val_loss: 12828.6465 - val_mae: 36.3111
Epoch 31/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7680.6250 - mae: 35.3800 - val_loss: 12873.0117 - val_mae: 36.6345
Epoch 32/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7755.2329 - mae: 35.7165 - val_loss: 12795.6465 - val_mae: 36.7085
Epoch 33/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7755.4082 - mae: 35.8721 - val_loss: 13038.5986 - val_mae: 36.7880
Epoch 34/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7954.2339 - mae: 35.8829 - val_loss: 12505.9375 - val_mae: 37.7354
Epoch 35/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7507.5903 - mae: 35.4005 - val_loss: 12327.0967 - val_mae: 36.6754
Epoch 36/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7605.1729 - mae: 35.4193 - val_loss: 13248.2949 - val_mae: 37.6241
Epoch 37/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7750.2598 - mae: 35.7363 - val_loss: 13899.6758 - val_mae: 36.5355
Epoch 38/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7969.7754 - mae: 35.1966 - val_loss: 13568.7080 - val_mae: 37.1715
Epoch 39/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7562.6899 - mae: 35.3152 - val_loss: 12765.8926 - val_mae: 36.5937
Epoch 40/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7585.9316 - mae: 34.8806 - val_loss: 13593.9170 - val_mae: 37.4431
Epoch 41/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7459.8452 - mae: 35.2341 - val_loss: 12538.5967 - val_mae: 36.7535
Epoch 42/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7457.7109 - mae: 35.3435 - val_loss: 12008.0479 - val_mae: 37.5369
Epoch 43/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7315.2080 - mae: 34.8798 - val_loss: 12675.3975 - val_mae: 36.4631
Epoch 44/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7692.5005 - mae: 35.2645 - val_loss: 12797.4414 - val_mae: 36.5216
Epoch 45/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7503.8994 - mae: 35.2207 - val_loss: 12169.4170 - val_mae: 36.1342
Epoch 46/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7295.5894 - mae: 34.6941 - val_loss: 12682.7100 - val_mae: 36.9348
Epoch 47/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7775.6060 - mae: 35.0481 - val_loss: 13510.0020 - val_mae: 36.7465
Epoch 48/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7727.9556 - mae: 35.3083 - val_loss: 12302.4844 - val_mae: 36.5248
Epoch 49/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7316.7754 - mae: 34.7038 - val_loss: 12119.8945 - val_mae: 36.5818
Epoch 50/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6981.7207 - mae: 34.4525 - val_loss: 13360.0576 - val_mae: 36.3713
Epoch 51/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7211.6157 - mae: 34.4007 - val_loss: 13034.1748 - val_mae: 36.2425
Epoch 52/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6951.9624 - mae: 34.1928 - val_loss: 12999.0723 - val_mae: 36.9458
Epoch 53/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7160.9111 - mae: 34.0648 - val_loss: 13073.5342 - val_mae: 36.3359
Epoch 54/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7467.7593 - mae: 34.7120 - val_loss: 14531.9375 - val_mae: 36.7810
Epoch 55/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7370.3013 - mae: 34.2629 - val_loss: 13525.9277 - val_mae: 36.6259
Epoch 56/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7219.2349 - mae: 34.1155 - val_loss: 13016.7324 - val_mae: 36.2781
Epoch 57/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7056.9482 - mae: 33.6447 - val_loss: 13802.6006 - val_mae: 37.8206
Epoch 58/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7382.0864 - mae: 34.1623 - val_loss: 12236.4238 - val_mae: 36.4292
Epoch 59/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7637.2529 - mae: 34.5879 - val_loss: 13519.8691 - val_mae: 36.1848
Epoch 60/60
264/264 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6988.1279 - mae: 33.6725 - val_loss: 13568.4941 - val_mae: 38.1114

## Evaluate the Model

## Hyperparameter Tuning (Find Best Parameters)

In [11]:
def build_regression_model(hp):
    model = Sequential()

    hp_units = hp.Int('units', min_value=64, max_value=256, step=64)
    model.add(Input(shape=(X_train_scaled.shape[1],)))
    model.add(Dense(units=hp_units, activation='relu'))
    model.add(Dropout(0.2))

    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))

    hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=hp_learning_rate),
        loss='mse',
        metrics=['mae']
    )

    return model

tuner = kt.RandomSearch(
    build_regression_model,
    objective='val_loss',
    max_trials=5,
    executions_per_trial=1,
    directory='my_dir',
    project_name='house_prices_tuning'
)

tuner.search(X_train_scaled, y_train, epochs=10, validation_split=0.2)

best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
print(f"Best Units: {best_hps.get('units')}")
print(f"Best Learning Rate: {best_hps.get('learning_rate')}")

Trial 5 Complete [00h 00m 17s]
val_loss: 20556.869140625

Best val_loss So Far: 12835.5478515625
Total elapsed time: 00h 01m 16s
Best Units: 192
Best Learning Rate: 0.01

In [12]:
mse, mae = model.evaluate(X_test_scaled, y_test)
print(f"Test Mean Absolute Error (MAE): {mae:.2f}")

83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7387.7271 - mae: 37.0895
Test Mean Absolute Error (MAE): 37.09